const test=require('node:test'),assert=require('node:assert/strict');
const {battingRates,pitchingRates}=require('../public/stats.js');
const {importCareer}=require('../public/ratings.js');
test('Batting denominators and total bases',()=>{const p=battingRates({AB:100,H:30,D:6,T:2,HR:4,BB:12,HBP:2,SF:1,SO:20});assert.equal(p.SLG,.52);assert.equal(p.OBP,44/115);assert.ok(Math.abs(p.ISO-.22)<1e-12);assert.equal(p.BABIP,26/77);assert.equal(p.PA,115);});
test('Outs rather than decimal innings and empty denominators',()=>{const p=pitchingRates({outs:10,H:3,BB:1,R:2,HR:1,HBP:1,SO:5,BF:15});assert.equal(p.IP,'3.1');assert.equal(p.WHIP,1.2);assert.ok(Math.abs(p.RA9-5.4)<1e-12);assert.ok(Math.abs(p.FIP-5.8)<1e-12);assert.equal(pitchingRates({outs:0}).RA9,null);});
test('Older saves do not invent total bases or FIP',()=>{assert.equal(battingRates({AB:10,H:3,HR:1,BB:0,HBP:0,SF:0,SO:1}).SLG,null);assert.equal(pitchingRates({outs:3,complete:false}).FIP,null);});
test('Career imports preserve the whole trajectory and choose entry age only once',()=>{const save={S:{name:'Career',pastab:{16:{con:30,spd:50},25:{con:80,spd:70}}},Seed:123};const p=importCareer(save);assert.equal(p.age,16);assert.equal(p.history['25'].contact,100);assert.equal(p.potential.contact,100);assert.equal(importCareer(save,25).contact,100);assert.throws(()=>importCareer(save,20));});
const {warContext,battingWAR,pitchingWAR}=require('../public/stats.js');
const batter=(extra={})=>({value_games:150,advance_runs:0,avoid_dp_runs:0,fielding_runs:0,arm_runs:0,catcher_throw_runs:0,G:150,AB:520,H:140,D:28,T:3,HR:20,BB:65,HBP:10,SF:5,SO:110,SB:10,CS:4,position_games:{CF:150},...extra});
const pitcher=(extra={})=>({G:30,GS:30,outs:540,H:160,R:70,HR:20,BB:50,HBP:5,SO:180,BF:740,complete:true,...extra});
test('Average hitter WAR has only replacement and position contributions',()=>{const p=batter(),c=warContext([p],[]),w=battingWAR(p,c);assert.equal(w.BatRuns,0);assert.ok(Math.abs(w.RunRuns)<1e-12);assert.ok(Math.abs(w.WAR-(20+2.5*150/162)/10)<1e-12);});
test('WAR scales with workload and sums across traded team stints',()=>{const p=batter(),half=Object.fromEntries(Object.entries(p).map(([k,v])=>[k,typeof v==='number'?v/2:v]));half.position_games={CF:75};const c=warContext([p],[]);assert.ok(Math.abs(battingWAR(p,c).WAR-2*battingWAR(half,c).WAR)<1e-12);});
test('Better hitting and pitching improve WAR; bad pitching can be negative',()=>{const p=batter(),better=batter({H:180}),c=warContext([p,better],[]);assert.ok(battingWAR(better,c).WAR>battingWAR(p,c).WAR);const q=pitcher(),bad=pitcher({HR:80,BB:150,SO:60}),d=warContext([],[q,bad]);assert.ok(pitchingWAR(q,d).WAR>pitchingWAR(bad,d).WAR);assert.ok(pitchingWAR(bad,d).WAR<0);});
test('Pitching league baseline is innings weighted',()=>{const a=pitcher(),b=pitcher({outs:27,HR:10});const c=warContext([],[a,b]);assert.ok(Math.abs(c.fip-(pitchingRates(a).FIP*180+pitchingRates(b).FIP*9)/189)<1e-12);assert.ok(Math.abs(pitchingWAR(a,warContext([],[a])).WAR-2)<1e-12);});
test('Missing historical counters or positions never invent WAR',()=>{const p=batter(),old={...p};delete old.D;assert.equal(warContext([p,old],[]).woba,null);assert.equal(battingWAR(p,warContext([p,old],[])).WAR,null);assert.equal(battingWAR({...p,position_games:{}},warContext([p],[])).WAR,null);assert.equal(pitchingWAR(pitcher(),warContext([],[pitcher({complete:false})])).WAR,null);});

test('Baserunning and defense enter WAR exactly once',()=>{const p=batter(),enhanced=batter({advance_runs:2,avoid_dp_runs:1,fielding_runs:4,arm_runs:1,catcher_throw_runs:2}),c=warContext([p],[]),before=battingWAR(p,c),after=battingWAR(enhanced,c);assert.equal(after.BaserunningRuns-before.BaserunningRuns,3);assert.equal(after.FieldRuns,7);assert.ok(Math.abs(after.WAR-before.WAR-1)<1e-12);assert.equal(after.BatRuns,before.BatRuns);assert.equal(after.RunRuns,before.RunRuns);});
test('Partial legacy coverage leaves full-season values unavailable',()=>{const p=batter({value_games:1,advance_runs:2}),c=warContext([p],[]);assert.equal(battingWAR(p,c).FieldRuns,null);assert.equal(battingWAR(p,c).BaserunningRuns,null);assert.equal(battingWAR(p,c).WAR,null);});
